type Room = {
  id: string;
  title: string;
  isPublic: boolean;
  isAutoGenerated: boolean;
  createdAt: string;
};

export const getActivePublicRoom = async (): Promise<Room | null> => {
  return null; // Simula che non ci siano stanze
};

export const createRoom = async (data: {
  title: string;
  isPublic: boolean;
  isAutoGenerated: boolean;
  countdownStart: number;
}): Promise<Room> => {
  return {
    id: `room-${Math.random().toString(36).substring(7)}`,
    title: data.title,
    isPublic: data.isPublic,
    isAutoGenerated: data.isAutoGenerated,
    createdAt: new Date().toISOString(),
  };
};
